MOUSEKEY_ENABLE = yes     # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
# RGB_MATRIX_ENABLE = yes  # Enable this and disable RGBLight for better control
VIA_ENABLE      = yes    # Enable VIA on-the-fly simple customization
OLED_ENABLE     = yes
OLED_DRIVER_ENABLE = yes
OLED_DRIVER     = SSD1306
WPM_ENABLE      = yes
LTO_ENABLE      = yes    # Link Time Optimization, smaller firmware size
